  </div><!-- .inner -->

</div><!-- #content -->

<footer>

  <div class="pagetop"><a href="#"><img src="img/pagetop.png" alt="トップへ戻る" class="pc" /></a></div>

  <div class="footer-btn">
    <ul>
        <li><a href="#" target="_blank"><img src="img/sp/btn-web.png" alt="24時間WEB予約" class="sp"/></a></li>
        <li><a href="tel:<?php include("inc/tel.inc"); ?>" class="tel-link" onclick="gtag('event','tel-tap',{'event_category': 'click','event_label': 'label'});"><img src="img/sp/btn-tel2.png" alt="電話をかける" class="sp"/></a></li>
    </ul>
  </div>

  <div class="wow fadeInUp">
  
  <div class="footer-logo"><a href="./"><img src="img/footer-logo.png" alt="<?php include("inc/clinic_name.inc"); ?>"/></a></div>
  
  <div class="inner">

    <div class="footer-content clearfix">
      <div class="info">
          <div class="contact">
            <div class="title">Contact<span>ご予約はこちらから</span></div>
            <div class="address">
              <p><?php include("inc/postal.inc"); ?>　<?php include("inc/address.inc"); ?></p>
            </div>
            <div class="tel"><?php include("inc/tel_tap.inc"); ?></div>
            <div class="web"><a href="" target="_blank" class="btn-a2"><span>WEB予約はこちら</span></a></div>
          </div>
          <div class="title">Time<span>診療時間</span></div>
          <?php include("inc/time.inc"); ?>
        </div>

    <div class="footer-center">
        <div class="feature">
                <dl>
                    <dt>各種保険取り扱い</dt>
                    <dd>保険診療を主軸に診療を行っています。<br>
                    自由診療は選択肢の一環としてご説明し、ご希望の方に行います。</dd>
                </dl>
                <dl>
                    <dt>予約優先診療</dt>
                    <dd>待ち時間軽減のため<br>
                    ご予約はお電話(<?php include("inc/tel_tap.inc"); ?>)にてご連絡ください。</dd>
                </dl>
                <dl>
                    <dt>急患随時受付</dt>
                    <dd>柔軟に対応しております。混雑している場合はお待たせすることもございますので、ご来院いただく前に一度お電話(<?php include("inc/tel_tap.inc"); ?>)にてお問い合わせください。</dd>
                </dl>
        </div>
    </div>

      </div>

    </div>

  <div class="footer-map">
    <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3240.1679138820746!2d139.7087089511665!3d35.69748533658975!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x60188cc2c9de75ad%3A0xd3b769694c085d4!2z5pel5pys44OT44K544Kr5qCq5byP5Lya56S-!5e0!3m2!1sja!2sjp!4v1545703819609" width="100%" height="300" frameborder="0" style="border:0" allowfullscreen></iframe>
  </div>

  <div class="footer-link">
      <h3 class="wow fadeIn">連携している高次医療機関のご紹介</h3>
      <p>より専門的な検査・治療が必要だと思われる場合は、連携している高次医療機関をご紹介いたします。<br>
      どうぞ安心してご来院ください。</p>
      <ul>
        <li class="wow fadeInUp" data-wow-delay="0.1s"><a href="" target="_blank"><img src="img/bnr01.jpg" alt="<?php include("inc/area.inc"); ?>・<?php include("inc/clinic_name.inc"); ?>"/></a></li>
        <li class="wow fadeInUp" data-wow-delay="0.2s"><a href="" target="_blank"><img src="img/bnr02.jpg" alt="<?php include("inc/area.inc"); ?>・<?php include("inc/clinic_name.inc"); ?>"/></a></li>
        <li class="wow fadeInUp" data-wow-delay="0.3s"><a href="" target="_blank"><img src="img/bnr03.jpg" alt="<?php include("inc/area.inc"); ?>・<?php include("inc/clinic_name.inc"); ?>"/></a></li>
        <li class="wow fadeInUp" data-wow-delay="0.4s"><a href="" target="_blank"><img src="img/bnr04.jpg" alt="<?php include("inc/area.inc"); ?>・<?php include("inc/clinic_name.inc"); ?>"/></a></li>
        <li class="wow fadeInUp" data-wow-delay="0.5s"><a href="" target="_blank"><img src="img/bnr05.jpg" alt="<?php include("inc/area.inc"); ?>・<?php include("inc/clinic_name.inc"); ?>"/></a></li>
        <li class="wow fadeInUp" data-wow-delay="0.6s"><a href="" target="_blank"><img src="img/bnr06.jpg" alt="<?php include("inc/area.inc"); ?>・<?php include("inc/clinic_name.inc"); ?>"/></a></li>
        <li class="wow fadeInUp" data-wow-delay="0.7s"><a href="" target="_blank"><img src="img/bnr07.jpg" alt="<?php include("inc/area.inc"); ?>・<?php include("inc/clinic_name.inc"); ?>"/></a></li>
        <li class="wow fadeInUp" data-wow-delay="0.8s"><a href="" target="_blank"><img src="img/bnr08.jpg" alt="<?php include("inc/area.inc"); ?>・<?php include("inc/clinic_name.inc"); ?>"/></a></li>
      </ul>
  </div>

      <div class="footer-menu">
        <?php include("inc/navi_footer.inc"); ?>
      </div>


    <div class="copyright"><?php include("inc/copyright.inc"); ?></div>
    
  </div>

</footer>