<header>
  <div class="inner clearfix">
    <div class="logo">
      <a href="./"><img src="img/logo2.png" alt="<?php include("inc/area.inc"); ?>・<?php include("inc/clinic_name.inc"); ?>"/></a>
    </div>
    <div class="info">

      <div class="contact">
        <div class="time-box"><?php include("inc/time.inc"); ?></div>
        <div class="address">
          <p><?php include("inc/postal.inc"); ?><br><?php include("inc/address.inc"); ?></p>
          <div class="tel"><?php include("inc/tel_tap.inc"); ?></div>
          <div class="web"><a href="#" target="brank" class="btn-a"><span>WEB予約はこちら</span></a></div>
        </div>
      </div>
    </div>

    <div class="sp-header-menu">
      <ul>
        <li><a href="<?php include("inc/g_map_link.inc"); ?>" target="_blank"><img src="img/sp/btn-map.png" width="160" height="160" alt="地図"/></a></li>
        <li><img src="img/sp/btn-menu.png" width="160" height="160" alt="メニュー"/></li>
      </ul>
    </div>
  </div>
</header>
