<nav class="pc">
  <ul class="inner">
    <li><a href="./" class="current01"><span>トップページ<small>top</small></span></a></li>
    <li><a href="service.html" class="current02"><span>診療案内<small>service</small></span></a></li>
    <li><a href="staff.html" class="current03"><span>院長・スタッフ<small>staff</small></span></a></li>
    <li><a href="clinic.html" class="current04"><span>医院・設備<small>clinic</small></span></a></li>
    <li><a href="access.html" class="current05"><span>アクセス<small>access</small></span></a></li>
    <li><a href="" class="current06"><span>ブログ<small>blog</small></span></a></li>
  </ul>
</nav>

<div id="content">
  <div class="">