      <ul>
        <li><a href="./" class="current01"><span>トップ</span></a></li>
        <li><a href="service.html" class="current02"><span>診療案内</span></a></li>
        <li><a href="staff.html" class="current03"><span>院長・スタッフ</span></a></li>
        <li><a href="clinic.html" class="current04"><span>院内・設備</span></a></li>
        <li><a href="access.html" class="current05"><span>アクセス</span></a></li>
        <li><a href="" class="current06"><span>ブログ</span></a></li>
      </ul>